### ISSUE TITLE
Babel 7 

### ISSUE THREAD

**Issue by codejunkienick** [gajus/babel-plugin-react-css-modules#137]
Is this still being prepared for babel 7 support? it's in beta now so would be worth preparing this plugin. Right now I get `_getClassName is not defined` whenever I use conditional stylenames

**Comment by gajus** [comment]
> Is this still being prepared for babel 7 support? it's in beta now so would be worth preparing this plugin. Right now I get _getClassName is not defined whenever I use conditional stylenames

I am not going to have time for this upgrade any time soon. Therefore, PR is welcome.

**Comment by cjanik** [comment]
I might be interested in contributing to this. Right now I have no familiarity with the plugin source though. Any ideas what the scope of the issue is, or where to start?

**Comment by gajus** [comment]
https://babeljs.io/blog/2017/03/01/upgrade-to-babel-7-for-tool-authors

**Comment by loganfsmyth** [comment]
For anyone looking to jump into this, I'll throw out a guess that this is similar to the issue in https://github.com/babel/babel/pull/6374 where the same `_getClassName` `Identifier` node is inserted into multiple places in the tree. The fix is probably the same. Needs calls to `t.clone` to copy the identifier each place that it is inserted into the AST.

**Comment by IanVS** [comment]
I'm guessing this can be closed now, right?

**Comment by gajus** [comment]
> I'm guessing this can be closed now, right?

This plugin doesn't support Babel 7, though.

**Comment by IanVS** [comment]
Then what do the 4.0.0 release notes mean? 

>BREAKING CHANGES
>babel 7 requirement

**Comment by gajus** [comment]
Never mind. Juggling too many projects at once.
