### ISSUE TITLE
With Next.js 2.0 module how to use it?

### ISSUE THREAD

**Issue by XOneto9** [gajus/babel-plugin-react-css-modules#140]
Hi,

I'm trying now for 11h to solve the problem for setup the plugin on my project app.
all of config file, I followed 'Readme script'.

and I use Create-react-app module.

1. if I use postcss-scss with changing .babelrc config as said on the guide, it gonna error.
with 
```
A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`

For more detailed information on preset configuration, please see http://babeljs.io/docs/plugins/#pluginpresets-options.
```
except for .babelrc, I'm not any other handle..

>>>My .babelrc
```

{
  "presets": [
    "react-app"
  ],
  "plugins": [
    ["react-hot-loader/babel"],
    ["react-css-modules", {
      "webpackHotModuleReloading": "true",
      "generateScopedName": "[path]___[name]__[local]___[hash:base64:5]"
    }]
  ],
  "filetypes": {
    ".scss": {
      "syntax": "postcss-scss",
      "plugins": ["postcss-nested"]
    }
  }
}
```

2. To remove filetype options on .babelrc, then code work!
 on the js file, however, The name 'className' was changed to 'styleName' it is now work css.

those are my problem.

Thank you

**Comment by XOneto9** [comment]
I solved the problem.
with Create-react-app modules, I'm handle a Webpack config file!

**Comment by XOneto9** [comment]
Sorry, re-open.

well, The above problem with CRA(Create-react-app) is solved to change Webpack config.

In project with Next.js, however, It is little hard to run the project.

The Next.js is said that Next.js is recommended to use babel plugin instant of directly changed the config file.
So, I just set the 'babel-plugin-react-css-modules' in my .babelrc file.
but the modules do not work.

So, I have a wonder that is it a possible using a babel-plugin-react-css-modules with Next.js modeule?

**Comment by trongthanh** [comment]
This question is old but still open. Let me try to answer so that it'll be helpful for anyone looking for help with Next.js. The short answer is Yes.

Next.js works with CSS module out of the box (with .module.css extension). However, the whole point of using this babel plugin is to be able to use `styleName` with pre-transformed class name strings.  

Here's  the config I extracted from a POC I'm working on:

In package.json, I already installed (related to Next.js and this question only):
```json
{
  "dependencies": {
    "@zeit/next-sass": "^1.0.1",
    "next": "9.1.7",
    "node-sass": "^4.13.1",
    "react": "16.12.0",
    "react-dom": "16.12.0"
  },
  "devDependencies": {
    "babel-plugin-react-css-modules": "^5.2.6",
    "postcss-scss": "^2.0.0"
  }
}
```

The `next.config.js` file:

```js
const withSass = require('@zeit/next-sass');

let nextConfig = withSass({
  cssModules: true,
  cssLoaderOptions: {
    importLoaders: 1,
    localIdentName: '[local]__[hash:base64:5]',
  },
});
/* other configs ... */
module.exports = nextConfig;
```

The `.babelrc` config:

```json
{
  "presets": ["next/babel"],
  "plugins": [
    [
      "babel-plugin-react-css-modules", {
        "filetypes": {
          ".scss": {
            "syntax": "postcss-scss"
          }
        },
        "generateScopedName": "[local]__[hash:base64:5]"
      }
    ]
  ]
}
```

The key point here is that  `localIdentName` in *next.config.js* should match `generateScopedName` in *.babelrc*. It's one of the issues I faced when I first tried this plugin and it didn't work.
