### ISSUE TITLE
react-datepicker styling not getting apply.  

### ISSUE THREAD

**Issue by Bhushankumar-pawar** [gajus/babel-plugin-react-css-modules#259]
I used react-datepicker, datePicker is successfully rendered but without styling 
<img width="744" alt="datePicker_issue" src="https://user-images.githubusercontent.com/23053040/60263817-426c7f80-98ff-11e9-8b7b-36ba6b3ab11f.PNG">

`
// webpack.config.js
```
{
      test: /\.css$/,
      use: [{ 
        loader: "style-loader"
      },{
        loader: miniCssExtractPlugin.loader,
        options: {
          sourceMap: true,
          publicPath: "../"
        }
      }, {
        loader: "css-loader",
        options: {
          importLoaders: 1,
          modules: true,
          localIdentName: '[path]___[name]__[local]___[hash:base64:5]',
          context
        }
      }, {
        loader: "postcss-loader"
      }],
    }
```

**Comment by gajus** [comment]
Issue does not provide sufficient context to determine the cause of the issue.

**Comment by Bhushankumar-pawar** [comment]
This issues happens wile migrating from react-css-modules to babel-plugin-react-css module. 
Date picker is working fine with react-css-modules  but with babel-plugin-react-css module styling of date picker not getting applied. 

Please check attach screenshot with react-css-module  and screen shot mention in ticket. 

<img width="302" alt="Screen Shot 2019-06-27 at 8 51 50 PM" src="https://user-images.githubusercontent.com/23053040/60278660-748cda00-991d-11e9-9712-4fdc9e0fa249.png">

**Comment by AlbertLucianto** [comment]
@Bhushankumar-pawar I think the problem is imported css files from external packages are inadvertently converted into css-modules. Try using different loader configs for imported css from node_modules. Maybe below config can solve your problem.

Webpack config ([Rule.oneOf](https://webpack.js.org/configuration/module/#ruleoneof)):

```js
{
  test: /\.css$/,
  oneOf: [
    {
      resourceQuery: /node_modules/,
      use: [/* your configs, but remove the options on "css-loader" */]
    },
    {
      use: [/* your configs */]
    }
  ]
}
```

And in your babel config for this plugin, add `exclude: 'node_modules'` ([options.exclude](https://github.com/gajus/babel-plugin-react-css-modules#options)) option.

This should fix not only `react-datepicker`, but also for other libraries that require import css stylings.
