### ISSUE TITLE
error when importing module the webpack way

### ISSUE THREAD

**Issue by craigcosmo** [gajus/babel-plugin-react-css-modules#27]
```js
import `css!sass!./style.css`
```
Will give you error. This plugin is trying to resolve that module name as `css!sass!./style.css` instead of `style.css`

**Comment by craigcosmo** [comment]
is there anyone having this issue as well?

**Comment by gajus** [comment]
This is webpack specific loader syntax. It is not supported at the moment.

There are no plans to add support for it – this syntax has been deprecated and will be removed in future webpack versions. (I cannot find where this is documented at the moment. Maybe I am wrong.)

Regardless, webpack documentation advises against using this syntax:

> Note: Avoid using this, if at all possible, if you intend your scripts to be environment agnostic (node.js and browser). Use the configuration convention for specifying loaders (see next section).

– https://webpack.github.io/docs/using-loaders.html#loaders-in-require

**Comment by RISCfuture** [comment]
There is a valid use case for this scenario though. In some cases you may want to one-off load CSS a different way, using different loaders. For example, in my project, I have one case where I want to load the CSS using `css-object-loader` instead of my normal CSS loader pipeline, because I use the CSS differently.
