### ISSUE TITLE
stylus import support

### ISSUE THREAD

**Issue by leecade** [gajus/babel-plugin-react-css-modules#9]
```jsx
import './index.module.styl'
```

got error:

```
Cannot use styleName attribute without importing at least one stylesheet.
```

**Comment by jcdekoning** [comment]
I am not sure if stylus is the same as sugarss (syntax seems quite the same). I made a PR (https://github.com/gajus/babel-plugin-react-css-modules/pull/10) which makes it possible to configure syntax parser.

`{
        "generateScopedName": "[name]__[local]",
        "filetypes": {
          ".sss": "sugarss"
        }
      }`

**Comment by gajus** [comment]
Fixed in https://github.com/gajus/babel-plugin-react-css-modules/pull/10.

Thanks to @jcdekoning .

**Comment by k1sul1** [comment]
It's possible to configure syntax parsers, but unfortunately Stylus doesn't work, because there isn't  a PostCSS parser available for it. 

SugarSS syntax is not the same.  Maybe it is if you use Stylus without braces, but not using braces breaks the parser way too easily with a cryptic error, indent based syntax is just not worth it. It's also not just braces, some may love their semicolons, the point is that Stylus is a very unopionated about syntax, so the parser also has to be like that.

I got an error with `sugarss` from the first line of my first `styl` file:
```
Module build failed: CssSyntaxError: /home/k1sul1/projects/redacted/src/index.styl:1:6: Unnecessary curly bracket
```

It doesn't look like it's happening: https://github.com/postcss/postcss/issues/602#issuecomment-149518623

As for me, I'm probably going to have to use SCSS instead of Stylus.
