### ISSUE TITLE
Global styles?

### ISSUE THREAD

**Issue by oshalygin** [gajus/babel-plugin-react-css-modules#91]
I tried this all sorts of ways but this doesn't work like the `react-css-modules` project which allows you to do the following:

`import '!style!css!../node_modules/bootstrap/dist/css/bootstrap.min.css';`

how do you import global styles with this project?

**Comment by ramasilveyra** [comment]
A pattern for deal with css modules files and global css files is to use the `.module.css` file name convention, more info here https://github.com/webpack-contrib/css-loader/issues/308.
If you adopt that you could use the [exclude option](https://github.com/gajus/babel-plugin-react-css-modules#configuration) with a regex that matches files that don't end in `.module.css` (`/.*[^.module.css]$/` probably, not tested).

**Comment by oshalygin** [comment]
Solid advice, to get this working with a similar approach, when importing the global style, use the minified version.  so `.*[^.min.css]`

**Comment by oshalygin** [comment]
Closing this out as there's a clear solution in mind.

**Comment by mohandere** [comment]
Hi @oshalygin 
I am trying the same with create-react-app by ejecting app. 

```
import styles from './App.css';
import 'bootstrap/dist/css/bootstrap.css';
```

Still i am unable to make bootstrap css work. Can you guys please provide an sample codes ?

Thank you so much for this feature.

**Comment by jasonk** [comment]
I realize I'm responding to a really old ticket, but I found my way here from Google while trying to figure out exactly how the exclude option works.  So I thought I would provide some info for any future travellers who stumble across this.

If you are having problems with this and you used one of the regexps that were posted in the issue:

* `.*[^.module.css]$` does not mean "exclude files that don't end with `.module.css`", it means "exclude files that do not end with `.`, `m`, `o`, `d`, `u`, `l`, `e`, `c`, or `s`"
* `.*[^.min.css]` does not mean "exclude files that don't end with `.min.css`", it means "exclude files that do not include `.`, `m`, `i`, `n`, `c`, or `s`"

For the first case, you can use: `^(?!.*[.]module[.]css$).*$` or the overly verbose `[^.][^m][^o][^d][^e][^.][^c][^s][^s]$`.

For the second case I would suggest you probably want to exclude files that end with `.min.css` rather than excluding them if they aren't minified.  In that case . you can just use `exclude : "[.]min[.]css$"`.
