### ISSUE TITLE
Difference from react-css-modules

### ISSUE THREAD

**Issue by dsempel** [gajus/babel-plugin-react-css-modules#96]
I would like to replace `react-css-modules` with this babel plugin in a project, since it seems like a better solution. What worries me is this line from `react-css-modules` readme:

> babel-plugin-react-css-modules is not a drop-in replacement and does not cover all the use cases of react-css-modules.

But the section `Difference from react-css-modules` basically says the only difference is better performance. I did a small test and it worked well, but could you elaborate more on what use cases are not covered by this plugin? Thank you!

**Comment by gajus** [comment]
> babel-plugin-react-css-modules is not a drop-in replacement and does not cover all the use cases of react-css-modules.

Its been a while since I've written this. I cannot recall for the rationale for phrasing it this way.

For the most part, it is a drop-in replacement.

The only differences that I can think at the moment:

1. There is no standard way to override styles at the run time. `react-css-modules` had [`styles` property](https://github.com/gajus/react-css-modules#styles-property).
2. `babel-plugin-react-css-modules` requires to use different syntax depending on whether you import one style per file or multiple styles. See https://github.com/gajus/babel-plugin-react-css-modules#conventions

Everything else is the same.

**Comment by dsempel** [comment]
Ok great! I was aware of the different syntax, but it's good to know I will probably not run into much problems while replacing `react-css-modules`. Thanks.
